### PR TITLE
aes: make autodetect unions non-Copy; MSRV 1.49+

### PR DESCRIPTION
**Pull request by tarcieri**
Uses the new `core::mem::ManuallyDrop` feature to allow the inner types of unions to be non-`Copy`.

### CODE REVIEW

**Comment by tarcieri** [comment]
It works! 🎉 

I wouldn't suggest merging until 1.49 stable is out, but in the meantime, it's nice to see this will be possible soon.

**Comment by tarcieri** [comment]
Rust 1.49 is out 🎉 Merging this.

**Comment by newpavlov** [comment]
It creates a bit of a problem. Previously MSRV was bound by `block-cipher`/`cipher` and was the same for all crates. Also IIUC by enabling the `enofrce-soft` the crate can be compiled on older Rust. Either way we would have to somehow explain this situation in the README. Maybe by adding an MSRV row to the table?

**Comment by tarcieri** [comment]
Yeah we can potentially add and CI for a lower MSRV with the `force-soft` feature enabled.

**Pull request merged**
