### PR TITLE
Add block-modes::IvState trait

### PR DESCRIPTION
**Pull request by zugzwang**
The new IvState trait allows to expose a value that can be used as an IV
for initializing a subsequent BlockMode. These values must be used exclusively
to resume cipher operations, and they MUST NOT be exposed to parties controlling
future blocks.

- Add tests that check correctness of interrupted encryptions (i.e.,
encrypting `k` blocks, initialize a new cipher with the IV returned by
iv_state, and encrypting the remaining blocks).
- Add OFB test.

cc @jethrogb

https://github.com/RustCrypto/block-ciphers/issues/226

### CODE REVIEW

**Comment by zugzwang** [comment]
Note: Defined the new trait instead of adding a method to `BlockMode` because some mode states cannot be completely determined by a value comparable to the initial IV (for instance, GOST-CBC, also implementing `BlockMode` needs a positional parameter also).

**Comment by newpavlov** [comment]
Note that you are working on a branch which has migrated to `cipher v0.3`, which is currently under development. So the release of these changes will be blocked on its release. We plan to do it before the end of February. Also we probably will move block mode traits into the `cipher` crate with some re-designs (though I still haven't found a good final design...).

And note that your code is incorrect for the CFB mode. Currently we pre-encrypt IV on initialization, so your `IvState` implementation will simply return an encrypted IV, which when used for re-initialization will result in a doubly encrypted IV. The simplest solution would be to decrypt IV, but a proper one would be to remove the per-encryption, since it's the only mode which does that.

**Comment by zugzwang** [comment]
Thanks @newpavlov for the heads-up on OFB. I wonder now why `ofb_aes128_continued` passes.

**Comment by jethrogb** [comment]
> Also we probably will move block mode traits into the cipher crate with some re-designs (though I still haven't found a good final design...).

What are your thoughts? Is there an issue for this? One thing that's missing today is an update/finish API but it's not too hard to build that on top of encrypt_blocks.

**Comment by zugzwang** [comment]
(Note on last commit: now, CFB doesn't encrypt the IV on initialization and works properly, but needs one IV decryption on parallel CFB decryption. I can refactor CFB parallel decryption to avoid this, if necessary).

**Comment by newpavlov** [comment]
Thank you! As mentioned earlier we will release these changes after the work on `cipher v0.3` is finished.

>What are your thoughts? Is there an issue for this?

No issue I am afraid. I though about exposing the fact that some modes only need block cipher encryption, while others require both encryption and decryption (in `cipher v0.3` we have introduced separate `BlockEncrypt` and `BlockDecrypt` traits). Also I thought about bringing back separate types for encryptors and decryptors. And finally about splitting the trait into two parts: core which works only on blocks (and thus padding-independent) and a buffered wrapper on top of it which would work with slices and will be generic over padding.

**Comment by jethrogb** [comment]
> And finally about splitting the trait into two parts: core which works only on blocks (and thus padding-independent) and a buffered wrapper on top of it which would work with slices and will be generic over padding.

Yes I think this would be helpful

**Pull request merged**
