### PR TITLE
Fixslice AES decryption

### PR DESCRIPTION
**Pull request by peterdettman**
All aes-soft operations now use fixslice code.
I've left bitslice.rs, consts.rs, expand.rs in the tree though they're no longer referenced.

### CODE REVIEW

**Comment by tarcieri** [comment]
> I've left bitslice.rs, consts.rs, expand.rs in the tree though they're no longer referenced.

I think at this point you can go ahead and remove them (along with the `byteorder` dependency in `Cargo.toml`).

**Comment by peterdettman** [comment]
Done. Rebased.

**Comment by tarcieri** [comment]
Performance is looking great (in relative terms, anyway):

```
test aes128_decrypt  ... bench:         333 ns/iter (+/- 81) = 48 MB/s
test aes128_decrypt8 ... bench:         663 ns/iter (+/- 102) = 193 MB/s
test aes128_encrypt  ... bench:         297 ns/iter (+/- 162) = 53 MB/s
test aes128_encrypt8 ... bench:         576 ns/iter (+/- 52) = 222 MB/s
```

```
test aes192_decrypt  ... bench:         399 ns/iter (+/- 93) = 40 MB/s
test aes192_decrypt8 ... bench:         797 ns/iter (+/- 97) = 160 MB/s
test aes192_encrypt  ... bench:         353 ns/iter (+/- 30) = 45 MB/s
test aes192_encrypt8 ... bench:         699 ns/iter (+/- 52) = 183 MB/s
```

```
test aes256_decrypt  ... bench:         488 ns/iter (+/- 74) = 32 MB/s
test aes256_decrypt8 ... bench:         954 ns/iter (+/- 66) = 134 MB/s
test aes256_encrypt  ... bench:         420 ns/iter (+/- 92) = 38 MB/s
test aes256_encrypt8 ... bench:         814 ns/iter (+/- 132) = 157 MB/s
```

**Comment by tarcieri** [comment]
@peterdettman I can cut another `aes-soft` release, unless you have additional optimizations you'd like to do first

**Comment by peterdettman** [comment]
@tarcieri Nothing immediate, no.

Probably the inv_sbox could be optimized a bit. [The fixslice paper](https://eprint.iacr.org/2020/1123) mentioned "an ARM-specific instruction scheduler" used by Schwabe and Stoffelen to generate this sbox code, so maybe someone could chase that up at some point.

**Comment by tarcieri** [comment]
@peterdettman might be referring to this https://github.com/Ko-/aes-armcortexm

**Comment by peterdettman** [comment]
@tarcieri Hmmm, give me an hour to play with that.

**Comment by tarcieri** [comment]
Already cut a release: #188 😅 

I can always cut an additional one, though

**Pull request merged**
