### PR TITLE
Performance improvements in aes_soft

### PR DESCRIPTION
**Pull request by peterdettman**
Improved performance for the aes_soft AES implementation:
- rewrite of mix_columns to remove duplicate expressions and clarify.
- rewrite of inv_mix_columns to remove duplicate expressions and reduce overall operations.
- rewrite (inv_)shift_row methods for u16 to use "delta swaps", saving several operations.
- a small tweak to inv_mcol, used only for the decryption key schedule.

### CODE REVIEW

**Comment by tarcieri** [comment]
See also: #162 

This might be good as an interim step, though

**Comment by jack-signal** [comment]
Just out of curiosity, did you try implementing InvMixColumns using the matrix decomposition

```
   | 0e 0b 0d 09 |   | 02 03 01 01 |   | 05 00 04 00 |
   | 09 0e 0b 0d | = | 01 02 03 01 | x | 00 05 00 04 |
   | 0d 09 0e 0b |   | 01 01 02 03 |   | 04 00 05 00 |
   | 0b 0d 09 0e |   | 03 01 01 02 |   | 00 04 00 05 |
```

The first matrix is the MixColumns matrix and the second is sparse. In a somewhat similar sliced AES implementation I found it led to an overall improvement of decryption performance by > 5%, plus you can save a bit of codesize by sharing the first multiplication with MixColumns.

**Comment by peterdettman** [comment]
@jack-signal I believe that the method in this PR uses the same total number of XORs as the decomposition you refer to, but avoids the extra 8 rotates that would be involved in the multiplication by `| 05 00 04 00 |`.

**Review by newpavlov — APPROVED** [review]
Thank you!

**Pull request merged**
