### PR TITLE
Apply clippy lints

### PR DESCRIPTION
**Pull request by luisbg**
This is cleaner and more explicit.

### CODE REVIEW

**Comment by luisbg** [comment]
Added a bunch of more fixes. Let me know which ones you like or if you want me to remove any.

**Comment by luisbg** [comment]
No problem. I will add that cfg_attr and push again. It will probably be tomorrow since I'm about to go offline.

**Comment by luisbg** [comment]
Let me know if the latest update to the PR is what you wanted :)

**Comment by newpavlov** [comment]
Yes, looks good! Thank you!

**Pull request merged**
